export const plugins = [require("@tailwindcss/typography"), require("daisyui")];
export const daisyui = {
  styled: true,
  themes: [
    {
      catppuccin: {
        "primary": "#d20f39",
        "secondary": "#40a02b",
        "accent": "#df8e1d",
        "neutral": "#3d4451",
        "base-100": "#eff1f5",
        "info": "#04a5e5",
        "success": "#40a02b",
        "warning": "#fe640b",
        "error": "#e64553"
      },
    },
    "light",
    "dark",
    "cupcake",
    "bumblebee",
    "emerald",
    "corporate",
    "synthwave",
    "retro",
    "cyberpunk",
    "valentine",
    "halloween",
    "garden",
    "forest",
    "aqua",
    "lofi",
    "pastel",
    "fantasy",
    "wireframe",
    "black",
    "luxury",
    "dracula",
    "cmyk",
    "autumn",
    "business",
    "acid",
    "lemonade",
    "night",
    "coffee",
    "winter",
  ],
  base: true,
  utils: true,
  logs: true,
  rtl: false,
  prefix: "",
};