<template>
<span class="tooltip" :data-tip="genre == 'Reincarnation' ? 'Reenkarnasyon' : genre == 'Action' ? 'Aksiyon' : genre == 'Romance' ? 'Romantik' : genre == 'Comedy' ? 'Komedi' : genre == 'Adventure' ? 'Macera' : genre == 'Magic' ? 'Büyü' : genre == 'Drama' ? 'Dram' : genre == 'Fantasy' ? 'Fantezi' : genre == 'Adaptation' ? 'Adaptasyon' : genre == 'Thriller' ? 'Gerilim' : genre == 'Award Winning' ? 'Ödüllü' : genre == 'Monsters' ? 'Canavarlar' : genre == 'Psychological' ? 'Psikolojik' : genre == 'Crime' ? 'Suç' : genre == 'Survival' ? 'Hayatta Kalma' : genre == 'Martial Arts' ? 'Dövüş Sanatları' : genre == 'Mafia' ? 'Mafya' : genre == 'Military' ? 'Askeri' : genre == 'Philosophical' ? 'Felsefi' : genre == 'Gore' ? 'Kan' : genre == 'Medical' ? 'Tıbbi' : genre == 'School Life' ? 'Okul Yaşamı' : genre == 'Horror' ? 'Korku' : genre == 'Police' ? 'Polisiye' : genre == 'Slice of Life' ? 'Yaşamdan Kesit' : genre == 'Mystery' ? 'Gizem' : genre == 'Tragedy' ? 'Trajedi' : genre == 'Demons' ? 'İblisler' : genre == 'Monster Girls' ? 'Canavar Kızlar' : genre == 'Supernatural' ? 'Doğaüstü' : genre == 'Samurai' ? 'Samuray' : genre == 'Time Travel' ? 'Zaman Yolculuğu' : genre == 'Full Color' ? 'Tamamen Renkli' : genre == `Boys' Love` ? 'Yaoi' : genre == 'Music' ? 'Müzik' : genre == `Girls' Love` ? 'Yuri' : genre == 'Vampires' ? 'Vampirler' : genre == 'Web Comic' ? 'Web Çizgi Romanı' : genre == 'Cooking' ? 'Yemek' : genre == 'Historical' ? 'Tarihi' : genre == 'Sci-Fi' ? 'Bilim Kurgu' : genre">
    <NuxtLink :class="`m-1 badge badge-lg no-underline ${genre == 'Award Winning' ? 'badge-accent' : genre == 'Gore' ? 'badge-error' : ''}`" :to="route.query.theme ? `/discover/?genres=${id}&theme=` + route.query.theme : `/manga/genre/${id}`">
          {{ genre == 'Reincarnation' ? 'Reenkarnasyon' : genre == 'Action' ? 'Aksiyon' : genre == 'Romance' ? 'Romantik' : genre == 'Comedy' ? 'Komedi' : genre == 'Adventure' ? 'Macera' : genre == 'Magic' ? 'Büyü' : genre == 'Drama' ? 'Dram' : genre == 'Fantasy' ? 'Fantezi' : genre == 'Adaptation' ? 'Adaptasyon' : genre == 'Thriller' ? 'Gerilim' : genre == 'Award Winning' ? 'Ödüllü' : genre == 'Monsters' ? 'Canavarlar' : genre == 'Psychological' ? 'Psikolojik' : genre == 'Crime' ? 'Suç' : genre == 'Survival' ? 'Hayatta Kalma' : genre == 'Martial Arts' ? 'Dövüş Sanatları' : genre == 'Mafia' ? 'Mafya' : genre == 'Military' ? 'Askeri' : genre == 'Philosophical' ? 'Felsefi' : genre == 'Gore' ? 'Kan' : genre == 'Medical' ? 'Tıbbi' : genre == 'School Life' ? 'Okul Yaşamı' : genre == 'Horror' ? 'Korku' : genre == 'Police' ? 'Polisiye' : genre == 'Slice of Life' ? 'Yaşamdan Kesit' : genre == 'Mystery' ? 'Gizem' : genre == 'Tragedy' ? 'Trajedi' : genre == 'Demons' ? 'İblisler' : genre == 'Monster Girls' ? 'Canavar Kızlar' : genre == 'Supernatural' ? 'Doğaüstü' : genre == 'Samurai' ? 'Samuray' : genre == 'Time Travel' ? 'Zaman Yolculuğu' : genre == 'Full Color' ? 'Tamamen Renkli' : genre == `Boys' Love` ? 'Yaoi' : genre == 'Music' ? 'Müzik' : genre == `Girls' Love` ? 'Yuri' : genre == 'Vampires' ? 'Vampirler' : genre == 'Web Comic' ? 'Web Çizgi Romanı' : genre == 'Cooking' ? 'Yemek' : genre == 'Historical' ? 'Tarihi' : genre == 'Sci-Fi' ? 'Bilim Kurgu' : genre }}
    </NuxtLink>
</span>
</template>
<script setup>
const route = useRoute()
const runtimeConfig = useRuntimeConfig();
const props = defineProps({
    genre: String,
    id: String
})
</script>