export const data = {
    orderOptions: [
        { value: "score", label: "Puan" },
        { value: "popularity", label: "Popülerlik" },
        { value: "members", label: "Üye" },
        { value: "favorites", label: "Favori" },
        { value: "rank", label: "Sıra" },
    ],
    genreIDs: [
        { id: "1", name: "Aksiyon" },
        { id: "2", name: "Macera" },
        { id: "3", name: "Arabalar" },
        { id: "4", name: "Komedi" },
        { id: "6", name: "Şeytan" },
        { id: "7", name: "Gizem" },
        { id: "8", name: "Drama" },
        { id: "9", name: "Ecchi" },
        { id: "10", name: "Fantastik" },
        { id: "11", name: "Oyun" },
        { id: "12", name: "Tarihi" },
        { id: "13", name: "Korku" },
        { id: "15", name: "Çocuk" },
        { id: "16", name: "Büyü" },
        { id: "17", name: "Dövüş Sanatları" },
        { id: "18", name: "Mecha" },
        { id: "19", name: "Müzik" },
        { id: "20", name: "Parodi" },
        { id: "21", name: "Samuray" },
        { id: "22", name: "Romantizm" },
        { id: "23", name: "Okul" },
        { id: "24", name: "Bilim Kurgu" },
        { id: "25", name: "Shoujo" },
        { id: "27", name: "Shounen" },
        { id: "29", name: "Uzay" },
        { id: "30", name: "Doğaüstü" },
        { id: "31", name: "Süper Güçler" },
        { id: "32", name: "Vampir" },
        { id: "33", name: "Yaoi" },
        { id: "34", name: "Yuri" },
        { id: "35", name: "Harem" },
        { id: "36", name: "Yaşamdan Kesitler" },
        { id: "37", name: "Spor" },
        { id: "38", name: "Seinen" },
        { id: "39", name: "Josei" },
        { id: "42", name: "Polisiye" },
        { id: "43", name: "Psikolojik" },
        { id: "44", name: "Seinen" },
        { id: "45", name: "Askeri" },
        { id: "46", name: "Gerilim" },
    ],
    status: [
        "Okunuyor",
        "Tamamlandı",
        "Beklemede",
        "Bırakıldı",
        "Planlandı",
        "Yeniden Okunuyor",
    ],
    statusSanity: [
        "reading",
        "completed",
        "onHold",
        "dropped",
        "planned",
        "rereading"
    ],
    statusMessages: {
        400: "Kötü istek",
        401: "Yetkisiz",
        403: "Yasaklandı",
        404: "Sayfa bulunamadı",
        405: "Method izin verilmiyor",
        409: "Çakışma",
        429: "Çok fazla istek",
        500: "Sunucu hatası",
        501: "Uygulanamadı",
        502: "Kötü ağ geçidi",
        503: "Hizmet kullanılamıyor",
        504: "Ağ geçidi zaman aşımına uğradı",
    },
    warnmessages: {
        58: "kan ve vahşet içerikleri",
        28: "toplumun ahlakına zarar verebilecek içerikler",
        26: "toplumun ahlakına zarar verebilecek içerikler",
        9: "yetişkin içerikleri",
        49: "yetişkin içerikleri",
        12: "yetişkin içerikleri",
        50: "yetişkin içerikleri",
        44: "toplumun ahlakına zarar verebilecek içerikler",
        35: "olumsuz örnek teşkil eden içerikler",
        65: "yetişkin içerikleri",
        74: "olumsuz örnek teşkil eden içerikler",
    },
    titletypes: {
        Default: ["Varsayılan", null],
        Synonym: ["Anlamdaş", null],
        Japanese: ["Japonca", "jp"],
        English: ["İngilizce", "gb-eng"],
        French: ["Fransızca", "fr"],
        German: ["Almanca", "de"],
        Spanish: ["İspanyolca", "es"],
        Portugese: ["Portekizce", "pt"],
        Italian: ["İtalyanca", "it"],
        Dutch: ["Flemenkçe", "nl"],
        Russian: ["Rusça", "ru"],
        Turkish: ["Türkçe", "tr"],
        Azerbaijani: ["Azerbaycan Dili", "az"],
        Kazakh: ["Kazakça", "kz"],
        Uzbek: ["Özbekçe", "uz"],
        Chinese: ["Çince", "tw"],
        Korean: ["Korece", "kr"],
        Arabic: ["Arapça", "ly"],
    },
    months: [
        "Ocak",
        "Şubat",
        "Mart",
        "Nisan",
        "Mayıs",
        "Haziran",
        "Temmuz",
        "Ağustos",
        "Eylül",
        "Ekim",
        "Kasım",
        "Aralık",
    ],
    malstatus: {
        Finished: "Yayın Tamamlandı",
        Publishing: "Yayınlanıyor",
        Discontinued: "Yayın Durduruldu",
        "On Hiatus": "Beklemede",
    },
    malgenres: {
        Action: "Aksiyon",
        Adventure: "Macera",
        "Avant Garde": "Avantgart",
        "Award Winning": "Ödüllü",
        "Boys Love": "Eril Eşcinsel",
        Comedy: "Komedi",
        Drama: "Dram",
        Fantasy: "Fantezi",
        "Girls Love": "Dişil Eşcinsel",
        Gourmet: "Gurme",
        Horror: "Korku",
        Mystery: "Gizem",
        Romance: "Romantik",
        "Sci-Fi": "Bilim Kurgu",
        "Slice of Life": "Yaşamdan Kesit",
        Sports: "Spor",
        Supernatural: "Doğaüstü",
        Suspense: "Gerilim",
        Ecchi: "Ecchi",
        Erotica: "Erotik",
        Hentai: "Hentai",
        "Adult Cast": "Yetişkin Karakter",
        Anthropomorphic: "Antropomorfik",
        CGDCT: "ŞKŞŞY",
        Childcare: "Çocuk Bakımı",
        "Combat Sports": "Dövüş Sporları",
        Crossdressing: "Travestilik",
        Delinquents: "Suçlular",
        Detective: "Dedektif",
        Educational: "Eğitici",
        "Gag Humor": "Mizah",
        Gore: "Vahşet",
        Harem: "Harem",
        "High Stakes Game": "Yüksek Bahisli Oyun",
        Historical: "Tarihsel",
        "Idols (Female)": "Dişil İdoller",
        "Idols (Male)": "Eril İdoller",
        Isekai: "Isekai",
        Iyashikei: "Iyashikei",
        "Love Polygon": "Aşk Çokgeni",
        "Magical Sex Shift": "Büyülü Cinsel Değişim",
        "Mahou Shoujo": "Büyülü Kız",
        "Martial Arts": "Dövüş Sanatları",
        Mecha: "Meka",
        Medical: "Tıbbi",
        Memoir: "Anısal",
        Military: "Askeri",
        Music: "Müzik",
        Mythology: "Mitoloji",
        "Organized Crime": "Organize Suç",
        "Otaku Culture": "Otaku Kültürü",
        Parody: "Parodi",
        "Performing Arts": "Sahne Sanatları",
        Pets: "Evcil Hayvanlar",
        Psychological: "Psikolojik",
        Racing: "Yarış",
        Reincarnation: "Reenkarnasyon",
        "Reverse Harem": "Ters Harem",
        "Romantic Subtext": "Romantik",
        Samurai: "Samuray",
        School: "Okul",
        Showbiz: "Şov Dünyası",
        Space: "Uzay",
        "Strategy Game": "Strateji Oyunu",
        "Super Power": "Süper Güç",
        Survival: "Hayatta Kalma",
        "Team Sports": "Takım Sporları",
        "Time Travel": "Zaman Yolculuğu",
        Vampire: "Vampir",
        "Video Game": "Video Oyunları",
        Villainess: "Düşmancıllık",
        "Visual Arts": "Görsel Sanatlar",
        Workplace: "İşyeri",
        Josei: "Josei",
        Kids: "Çocuklar",
        Seinen: "Seinen",
        Shoujo: "Shoujo",
        Shounen: "Shounen",
    },
};